### ISSUE TITLE
Frontend appears to not load completely

### ISSUE THREAD

**Issue by raman325** [home-assistant/iOS#1254]
**iOS device model, version and app version**

Model Name: iPhone 12 Pro
Software Version: 14.1
App version: 2020.7 (this affects the MacOS app as well)

**Home Assistant Core Version**
0.117.1

**Describe the bug**
Sometimes it looks like the frontend doesn't render completely - the text of the left-side menu either shows what looks like untranslated text, or nothing at all. In the MacOS app, I noticed that when I opened the command palette, the menu icons were shown but that text was missing too.

**To Reproduce**
Unclear, it happens sometimes when the app has been hard closed and I am opening it for the first time.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/7243222/97727445-c9f37100-1aa6-11eb-9d75-38403fd1899a.png)
![image](https://user-images.githubusercontent.com/7243222/97727496-db3c7d80-1aa6-11eb-8e97-e11d2c29e268.png)

**Additional context**
If I hard close the app and re-open it a couple of times, it eventually renders properly. This also appeared to have been introduced with the upgrade to 0.117.0

**Comment by alstr** [comment]
I am also experiencing this very frequently. Force closing the app and reopening does not always resolve the issue. Clearing frontend cache combined with force close is what seems to work but not sure if it does every time. Either way this is happening almost every time I open the app now. It's not just menu navigation labels disappearing/reverting to ID names, but various labels throughout the interface, which makes it very difficult to use.

![IMG_0980 (1)](https://user-images.githubusercontent.com/11612438/97849000-d0bdf600-1ce9-11eb-9f0a-5b0075a8bc37.jpeg)

Using version 0.117.1 with iOS 14.0.1.

**Comment by raman325** [comment]
Here's an example of an unactionable notification due to the issue: 
![image](https://user-images.githubusercontent.com/7243222/97934698-68e8c900-1d44-11eb-9817-92995d80cd73.png)

**Comment by TomBrien** [comment]
I have now seen this on a desktop so I think it is purely a frontend issue although the webview in app seems to be more susceptible

**Comment by TomBrien** [comment]
What language is everyone using? I'm `en_GB`.

**Comment by alstr** [comment]
> What language is everyone using? I'm `en_GB`.

I am using this also.

**Comment by raman325** [comment]
`en_US` for me

**Comment by TomBrien** [comment]
This is a frontend issue as reported in home-assistant/frontend#7512. Closing here as it isn't caused by the app.

**Comment by adamjernst** [comment]
Fixed in home-assistant/frontend#7597.

**Comment by ViViDboarder** [comment]
The listed PR has not fixed anything for me. This still happens from time to time. Currently, no amount of clearing front end cache and restating the app (iOS) is making any difference.

I’ve had no issues with Safari, which I’ve had to use in the interim while the app isn’t usable.

It could be an issue with Frontend still (and I kind of feel like it must…), but since I haven’t seen it in Safari yet, I thought I’d comment here first.

**Comment by adamjernst** [comment]
@ViViDboarder looks like @bramkragten fixed more race conditions in #7885 and #9499. In any case, probably best to open a new issue with full information (app version? frontend version? language you're using? etc) so we can help you out.
