### ISSUE TITLE
Apple M1: Facetime sensor always ON

### ISSUE THREAD

**Issue by LucasJanin** [home-assistant/iOS#1294]
**Device model, version and app version**

Model Name: Macbook Pro M1
macOS Version: 11.0.1
App Version: 2020.7 (10)
Safari Version: 14.0.1
Home Assistant Core Version: 0.118.4

**Describe the bug**
I recently switch to a Macbook Pro M1, the facetime sensor is always ON whatever the usage of the facetime camera.
No issue with the microphone sensor. I suppose it's related to the new hardware of Macbook Pro M1.

**To Reproduce**
Turn OFF and ON the camera, no change of the facetime sensor

**Expected behavior**
Turn OFF and ON the camera should change the facetime sensor

**Comment by zacwest** [comment]
It's unlikely I will have access to M1 hardware anytime soon, so we'll need to debug this remotely! Could you grab the logs from Preferences… > show logs in folder? They will contain personal information, so you can send them to me over Dropbox in [this file request](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y). I'll delete the files after looking for any hints. You can also grab just the logs between e.g. opening and closing Photo Booth so we can see what's happening.

**Comment by zacwest** [comment]
Looking at your logs, nothing is jumping out at me as incorrect. I am seeing the camera firing updates as though its state is changing:

```
[Info] [main] [InputDeviceSensor.swift:56] addObserver(object:property:) > info updated for coreMedia(33)
```

but every time we go to grab the 'in use' status, we're seeing it as 'true'. This may require some guess-and-check.

**Comment by LucasJanin** [comment]
Hi @zacwest ,

Let me know if I can help you with testing your guess-and-check.

Unfortunately, I'm not living in SF 
Thanks for your fast reply!

**Comment by LucasJanin** [comment]
Happy new year @zacwest,

Thanks for the new year version 2021.1 (5). 
FYI, the Facetime sensor always ON still present on my Apple M1.

**Comment by zacwest** [comment]
Filed this as FB8960241 with Apple. I'll record any updates here as they come.

A developer friend of mine was able to confirm that this is happening on additional M1 hardware. We also were able to determine that the system APIs are, in fact, returning the incorrect "on" state to the Home Assistant app; this error occurs in both HA and in other apps looking at the same value.

I do not believe there is any workaround possible; the only information we have is incorrect.

**Comment by LucasJanin** [comment]
Hi @zacwest,

Very happy to know the issue is confirmed and Apple knows the issue.
I'm using the microphone for now.

Thanks, for the update!

**Comment by ThomDietrich** [comment]
I'm also available for testing with a M1 and the same issue. Thanks for your great work!

**Comment by zacwest** [comment]
Apple reports this may be fixed in 11.4, which is now in developer beta. If anyone gets a chance to upgrade during its lifecycle, please let us know if it is indeed fixed.

**Comment by LucasJanin** [comment]
Nice! Unfortunately, I don't have anymore my Macbook Pro M1.

**Comment by ThomDietrich** [comment]
I can't switch to dev beta atm but I'll test as soon as it hits production ;)

**Comment by zacwest** [comment]
Looks like this is not resolved in 11.4 beta 1 (20F5046g).

**Comment by ajobbins** [comment]
Not fixed in 11.4 :(

**Comment by zacwest** [comment]
Looks like macOS 12.0 beta 3 fixes this issue.

**Comment by LucasJanin** [comment]
> Looks like macOS 12.0 beta 3 fixes this issue.

Great news! Just 2-3 months to wait for the final.

**Comment by zacwest** [comment]
Looks fixed in Monterey!

**Comment by LucasJanin** [comment]
Yes, thanks a lot @zacwest !!!!
My OnAir light is now fully functional :-)

**Comment by stoerr** [comment]
I just discovered by accident, that there is a apple13camerad process that always uses up 6.1 %GPU on my M1. So it sounds like this is not really solved. :-(

**Comment by kamekura** [comment]
I have the following related issue: no app is using the camera, Facetime sensor is off, but I when I try to use the camera in a browser app, no camera is found.

**Comment by ernestmalcolm** [comment]
Hi, I have an M1 Pro MacBook Pro, and the camera light issue is still there despite several updates. No apps are accessing the camera. When I use Facetime, upon quitting the app, the light goes off, then back on again, and stays on forever.

I tried following the thread but nothing new. Do you happen to have any updates on this??

**Comment by Rupinderpreet** [comment]
Hi, I have MacBook Air M1 on macOS 15.2 Sequoia, whenever I put my device on charging facetime turn ON the camera and keep using it in the background even when it is minimized until I quite facetime manually. This issue only happens in charging state, never on battery state.
