### ISSUE TITLE
unknown error:URLSessionTask failed with error

### ISSUE THREAD

**Issue by Blear** [home-assistant/iOS#1571]
**iOS device model, version and app version**

Model Name: ipad air 2
Software Version: 14.4.2
App version: 2021.3

**Home Assistant Core Version**

core-2021.3.4

**Describe the bug**
My Home Assistent lan address:http://192.168.199.100:8123 
App cant't discover my Home Assistant address..(wifi state is normal and ipad can discover airplay device in my home)
Configure the lan address of homeassistant, prompt:
unknown error:URLSessionTask failed with error :sees to have been disconnected from the Internet
When I use Internet address show connect button ， but there is no response to clicking it...
But in Safari, everything is normal,
and my iphoen x version:14.4, is normal,and it's Can automatically find my Home Assistant address

**Screenshots**

![199322657026491372](https://user-images.githubusercontent.com/5763006/113500469-c5991b80-9550-11eb-8d1d-4c6c98d63d9d.jpg)
![831698699788205623](https://user-images.githubusercontent.com/5763006/113500472-cc279300-9550-11eb-8f3b-42c2b888c95f.jpg)
![482046951946139593](https://user-images.githubusercontent.com/5763006/113500480-d47fce00-9550-11eb-81be-b65a17de2b73.jpg)

**Additional context**

**Comment by zacwest** [comment]
You may have denied local network access to the app. The system does not inform the app about whether you have denied permission. Open the Home Assistant entry in the system Settings app and verify that Local Network is enabled.

**Comment by Blear** [comment]
At first, I thought it was the IOS system problem. I tried to flash the ipad system, but the problem still existed

**Comment by Blear** [comment]
> 您可能已拒绝本地网络访问该应用程序。系统不会通知应用程序您是否已拒绝许可。在系统设置应用程序中打开家庭助理条目，并验证是否启用了本地网络。

Thank you very much. The problem is solved.

**Comment by klaus1k** [comment]
I experience the same issue, but I have Local network enabled. Upgraded HA Core today to 2021.4.1. Did work fine previously. Any ideas?

**Comment by schmjop** [comment]
Unfortunately I am facing the same issue with the same error message as @Blear.
The solution given by @zacwest did not solve the problem for me. I have tried several devices with no success.

I am running the Home Assistant Operating System in a UniFi network with the DuckDNS add-on.
