### ISSUE TITLE
Camera preview has wrong aspect ratio in notifications

### ISSUE THREAD

**Issue by efirestone** [home-assistant/iOS#167]
When previewing a camera in a push notification, the aspect ratio of the camera stream is wrong if the camera has a widescreen feed (see attached).

I believe you can make this change to fix it easily, or with a bit more work the view itself could be resized (assuming the notification actually respects that resulting size):

```
diff --git a/NotificationContentExtension/NotificationViewController.swift b/NotificationContentExtension/NotificationViewController.swift
index 6a1cfd8..b086bb9 100644
--- a/NotificationContentExtension/NotificationViewController.swift
+++ b/NotificationContentExtension/NotificationViewController.swift
@@ -43,6 +43,7 @@ class NotificationViewController: UIViewController, UNNotificationContentExtensi
         imageView.frame = self.view.frame
         // Needed for UI Automation w/ Fastlane Snapshot
         imageView.accessibilityIdentifier = "camera_notification_imageview"
+        imageView.contentMode = .scaleAspectFit
 
         var frameCount = 0
```

![img_1210](https://user-images.githubusercontent.com/656555/47258994-ff513700-d468-11e8-9b3a-fab25b2d7538.PNG)

**Comment by robbiet480** [comment]
@efirestone why don't you submit a PR to master that we'd be happy to accept so that you can get a little bit closer to that Hacktoberfest goal :)

**Comment by efirestone** [comment]
Would be happy to! But that’s a theoretical fix just from looking at the code. Is there a way to test notification fixes without having the signing certs for the app?

**Comment by daniarv** [comment]
Hi,
I have noticed the same thing with my cameras and I had a plan to change this attribute: `UNNotificationExtensionInitialContentSizeRatio`
My resolution for cameras and images is often widescreen format and my cameras have the resolution 1280x768. If I change this attribute to 0.6 the aspect ratio for the camera would be correct (I think).
I will then use Xcode to install the app on my iPhone.
Would of course be better with a solution that change the ratio automatically based on the attached image.

**Comment by robbiet480** [comment]
Fixed in 2.0

**Comment by daniarv** [comment]
> Fixed in 2.0

Hi,

I have 2.0 installed but it seems that the problem with the wrong aspect ratio is still there.
When pressing and holding on the notification I get a ratio of the live stream as in the first post.

**Comment by peterhollis** [comment]
There still appears to be an issue with the aspect ratio of the live stream. 

My current work around is cropping the image in Blue Iris but would love to be able to use the stream with the correct aspect ratio.

**Comment by robbiet480** [comment]
Closing in favor of #513.
