### ISSUE TITLE
Delayed script execution starts actions when no longer needed

### ISSUE THREAD

**Issue by eMeF1** [home-assistant/iOS#3526]
**iOS device model, version and app version**
Model Name: 
- Apple Watch Ultra 2, MREJ3CS/A

Software Version: 
- watchOS 11.3.1
- iOS 18.4 and 18.3.1 

App version: 
- Home Assistant Companion 2025.2 (2025.1178)

**Home Assistant Core Version**
- Home Assistant Core 2025.4.1
- Home Assistant Supervisor 2025.03.4
- Home Assistant Operating System 15.1

**Describe the bug**
Scripts started on Apple Watch are delayed and execute actions at the time when these are no longer needed. In particular, it relates to the Door Lock Open action. 

**To Reproduce**
Current behavior:

1. On the iOS Companion app, go to Apple Watch - Configuration
2. Under Items, tap +Add item
3. On the Script tab, select the desired script and Save the change
4. On WatchOS open Companion app and Reload 
5. Tab on the script added in previous steps
6. [This happens sporadically] Script start (spinning icon) - I'm not sure if the icon eventually displays the tick, but it returns to the script icon in the end and UI becomes available again
- `2025-04-05 11:12:50.684 AM [Verbose] [main] [WatchCommunicatorService.swift:59] setupMessages() > Received magicItemPressed InteractiveImmediateMessage(identifier: "magicItemPressed", content: ["itemId": script.open_home_door, "serverId": 8A243F93-0F97-4337-85E7-D58B18635F7F, "itemType": script], reply: (Function)) ["itemId": script.open_home_door, "serverId": 8A243F93-0F97-4337-85E7-D58B18635F7F, "itemType": script]`
8. The script's Action is not (yet) performed
9. Tab again on the script added in previous steps
10. Script start

- `2025-04-05 11:13:00.675 AM [Verbose] [main] [WatchCommunicatorService.swift:59] setupMessages() > Received magicItemPressed InteractiveImmediateMessage(identifier: "magicItemPressed", content: ["itemType": script, "itemId": script.open_home_door, "serverId": 8A243F93-0F97-4337-85E7-D58B18635F7F], reply: (Function)) ["itemType": script, "itemId": script.open_home_door, "serverId": 8A243F93-0F97-4337-85E7-D58B18635F7F]`

12. Action is performed (door opens)
- ![Image](https://github.com/user-attachments/assets/0e90fbf7-60d3-49a1-844d-0b79174989f6)
- ![Image](https://github.com/user-attachments/assets/9e98d280-f547-4c36-85f6-2c60a22b9248)

14. 3:50 later, the first run continues, and action is performed (door opens) again
- ![Image](https://github.com/user-attachments/assets/f98a5ef4-ce12-4dfc-a06c-68e25e130c5f)
- ![Image](https://github.com/user-attachments/assets/89e98c84-85af-4cb5-9f4d-8e82f5770341)
- ![Image](https://github.com/user-attachments/assets/1d1d231e-748a-4ae5-a70c-773de28b1998)
- ![Image](https://github.com/user-attachments/assets/d6313701-60c6-4a10-8d21-e46ad155b755)

Expected Behaviour
In step 12. the system recognizes a delayed script trigger and interrupts the execution.

**Additional context**

<details>
<summary>Home Assistant_2025-04-05_43941 PM.txt</summary>

```2025-04-05 11:12:50.614 AM [Info] [main] [Environment.swift:73] init() > WebSocket: disconnecting; permanently: false, error: Optional(HAKit.HAReconnectManagerError.lateFireReset)
2025-04-05 11:12:50.615 AM [Info] [main] [Environment.swift:73] init() > WebSocket: phase transition to disconnected(error: nil, forReset: true)
2025-04-05 11:12:50.664 AM [Info] [main] [SensorContainer.swift:223] updateSignaled(from:) > live update triggering from ConnectivitySensor
2025-04-05 11:12:50.680 AM [Verbose] [main] [WebViewExternalMessageHandler.swift:197] sendExternalBus(message:) > sending {"type":"command","command":"restart","id":-1}
2025-04-05 11:12:50.683 AM [Error] [main] [WebViewExternalMessageHandler.swift:200] sendExternalBus(message:) > failed to fire message to externalBus: Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}
2025-04-05 11:12:50.683 AM [Info] [main] [Environment.swift:73] init() > WebSocket: connecting using HAConnectionInfo(url: http://192.168.50.XXX:8123, userAgent: Optional("Home Assistant/2025.2 (io.robbie.HomeAssistant; build:2025.1178; iOS 18.4.0)"), engine: nil, evaluateCertificate: Optional((Function)))
2025-04-05 11:12:50.684 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: immediatelyReachable
2025-04-05 11:12:50.684 AM [Verbose] [main] [WatchCommunicatorService.swift:59] setupMessages() > Received magicItemPressed InteractiveImmediateMessage(identifier: "magicItemPressed", content: ["itemId": script.open_home_door, "serverId": XXXX-XXX-XXX-XXX-XXXX, "itemType": script], reply: (Function)) ["itemId": script.open_home_door, "serverId": XXXX-XXX-XXX-XXX-XXXX, "itemType": script]
2025-04-05 11:12:50.688 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:12:50.688 AM [Verbose] [main] [WatchCommunicatorService.swift:45] setup() > Received context: ["activeFamilies", "servers", "watchBatteryState", "watchBattery", "watchModel", "complications", "watchVersion", "SSID"] ["activeFamilies": <__NSSingleObjectArrayI 0x145b2c4e0>(
graphicCircular
)
, "servers": <...>, "watchBatteryState": 1, "watchBattery": 0.75, "watchModel": Watch7,5, "complications": <__NSArray0 0xxxxx20360>(

)
, "watchVersion": 11.3.1, "SSID": SSID]
2025-04-05 11:12:50.690 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 42), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseServiceCall), request(WebhookRequest(type: "call_service", data: ["service": "open_home_door", "service_data": [:], "domain": "script"], localMetadata: nil))
2025-04-05 11:12:50.697 AM [Verbose] [main] [ConnectivityWrapper.swift:113] syncNetworkInformation() > Current SSID: nil, current BSSID: nil
2025-04-05 11:12:50.698 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:130] configure(managers:) > manager SSID is active: false
2025-04-05 11:12:50.698 AM [Verbose] [main] [WatchCommunicatorService.swift:45] setup() > Received context: ["watchBatteryState", "activeFamilies", "watchBattery", "SSID", "complications", "servers", "watchVersion", "watchModel"] ["watchBatteryState": 1, "activeFamilies": <__NSSingleObjectArrayI 0x145b2c560>(
graphicCircular
)
, "watchBattery": 0.75, "SSID": SSID, "complications": <__NSArray0 0xxxxx20360>(

)
, "servers": <...>, "watchVersion": 11.3.1, "watchModel": Watch7,5]
2025-04-05 11:12:50.711 AM [Verbose] [main] [Realm+Initialization.swift:95] getRealm(objectTypes:) > Current schema version 28
2025-04-05 11:12:50.711 AM [Verbose] [main] [Realm+Initialization.swift:100] getRealm(objectTypes:) > Schema version defined: 28
2025-04-05 11:12:50.713 AM [Info] [main] [WatchHelpers.swift:68] SyncWatchContext() > updated context
2025-04-05 11:12:50.713 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:78] updateManagers() > 
2025-04-05 11:12:50.714 AM [Verbose] [com.apple.root.user-initiated-qos] [Realm+Initialization.swift:95] getRealm(objectTypes:) > Current schema version 28
2025-04-05 11:12:50.714 AM [Verbose] [com.apple.root.user-initiated-qos] [Realm+Initialization.swift:100] getRealm(objectTypes:) > Schema version defined: 28
2025-04-05 11:12:50.714 AM [Info] [main] [WebViewController.swift:744] loadActiveURLIfNeeded() > not loading, in background
2025-04-05 11:12:50.714 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:93] updateManagers() > configuring push for SSID: [XXXX-XXX-XXX-XXX-XXXX]
2025-04-05 11:12:50.714 AM [Verbose] [main] [NotificationManagerLocalPushInterfaceExtension.swift:141] configure(managers:) > computed managers: [XXXX-XXX-XXX-XXX-XXXX: [<NEAppPushManager: 0xxxxxxxxxx0>]]
2025-04-05 11:12:50.733 AM [Info] [com.apple.root.user-initiated-qos] [LegacyModelManager.swift:154] cleanup(using:realm:) > delete LocationHistoryEntry: 3
2025-04-05 11:12:50.769 AM [Info] [com.apple.root.user-initiated-qos] [RealmScene.swift:71] willDelete(objects:server:realm:) > deleting actions []
2025-04-05 11:12:50.772 AM [Info] [main] [HAAPI.swift:888] UpdateSensors(trigger:limitedTo:location:) > updating sensors ["activity", "pedometer_distance", "pedometer_floors_ascended", "pedometer_floors_descended", "pedometer_steps", "pedometer_avg_active_pace", "battery_level", "battery_state", "storage", "connectivity_ssid", "connectivity_bssid", "connectivity_connection_type", "connectivity_sim_1", "connectivity_sim_2", "focus", "last_update_trigger", "watch-battery", "watch-battery-state", "app-version", "location-permission", "iphone-audio-output"]
2025-04-05 11:12:50.798 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:12:50.802 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 43), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseUpdateSensors), request(WebhookRequest(type: "update_sensor_states", data: [["type": "sensor", "icon": "mdi:help-circle", "state": "Unknown", "attributes": ["Confidence": "High", "Types": ["Unknown"]], "unique_id": "activity"], ["icon": "mdi:hiking", "state": 388, "unique_id": "pedometer_distance", "type": "sensor"], ["unique_id": "pedometer_floors_ascended", "state": 1, "type": "sensor", "icon": "mdi:stairs-up"], ["state": 3, "unique_id": "pedometer_floors_descended", "type": "sensor", "icon": "mdi:stairs-down"], ["state": 544, "icon": "mdi:walk", "type": "sensor", "unique_id": "pedometer_steps"], ["state": 1, "unique_id": "pedometer_avg_active_pace", "icon": "mdi:speedometer", "type": "sensor"], ["unique_id": "battery_level", "attributes": [:], "type": "sensor", "state": 75, "icon": "mdi:battery-70"], ["state": "Not Charging", "attributes": ["Low Power Mode": false], "type": "sensor", "unique_id": "battery_state", "icon": "mdi:battery-70"], ["state": "30.64", "icon": "mdi:database", "attributes": ["Available (Opportunistic)": "78,32 GB", "Available": "39,14 GB", "Available (Important)": "104,89 GB", "Total": "255,64 GB"], "type": "sensor", "unique_id": "storage"], ["state": "SSID", "unique_id": "connectivity_ssid", "icon": "mdi:wifi", "type": "sensor"], ["icon": "mdi:wifi-star", "type": "sensor", "unique_id": "connectivity_bssid", "state": "f0:XX:XX:XX:XX:XX"], ["type": "sensor", "icon": "mdi:signal", "attributes": ["Cellular Technology": "5G"], "unique_id": "connectivity_connection_type", "state": "Cellular"], ["icon": "mdi:sim", "unique_id": "connectivity_sim_1", "attributes": ["ISO Country Code": "--", "Carrier Name": "--", "Carrier ID": "0000000000000000", "Allows VoIP": true, "Current Radio Technology": "5G Non-Standalone", "Mobile Network Code": "XXXXX", "Mobile Country Code": "XXXXX"], "state": "--", "type": "sensor"], ["icon": "mdi:sim", "unique_id": "connectivity_sim_2", "state": "--", "type": "sensor", "attributes": ["Carrier ID": "0000000100000002", "Carrier Name": "--", "Mobile Country Code": "XXXXX", "ISO Country Code": "--", "Allows VoIP": true, "Mobile Network Code": "XXXXX"]], ["state": false, "type": "binary_sensor", "icon": "mdi:moon-waning-crescent", "unique_id": "focus"], ["unique_id": "last_update_trigger", "type": "sensor", "icon": "mdi:cellphone-wireless", "state": "Signaled"], ["type": "sensor", "state": 75, "unique_id": "watch-battery", "icon": "mdi:battery-70"], ["state": "Not Charging", "type": "sensor", "unique_id": "watch-battery-state", "icon": "mdi:battery-70"], ["state": "2025.2", "type": "sensor", "unique_id": "app-version"], ["type": "sensor", "state": "Authorized Always", "unique_id": "location-permission", "icon": "mdi:map"], ["state": "Built-in Speaker", "icon": "mdi:volume-high", "unique_id": "iphone-audio-output", "type": "sensor"]], localMetadata: nil))
2025-04-05 11:12:50.803 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:191] updateManager(existingManager:ssid:servers:encoder:) > manager <NEAppPushManager: 0xxxxxxxxxx0> saved, error: nil
2025-04-05 11:12:50.899 AM [Info] [main] [HAAPI.swift:888] UpdateSensors(trigger:limitedTo:location:) > updating sensors ["activity", "pedometer_distance", "pedometer_floors_ascended", "pedometer_floors_descended", "pedometer_steps", "pedometer_avg_active_pace", "battery_level", "battery_state", "storage", "connectivity_ssid", "connectivity_bssid", "connectivity_connection_type", "connectivity_sim_1", "connectivity_sim_2", "focus", "last_update_trigger", "watch-battery", "watch-battery-state", "app-version", "location-permission", "iphone-audio-output"]
2025-04-05 11:12:50.900 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:12:50.904 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 44), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseUpdateSensors), request(WebhookRequest(type: "update_sensor_states", data: [["state": "Unknown", "type": "sensor", "unique_id": "activity", "attributes": ["Types": ["Unknown"], "Confidence": "High"], "icon": "mdi:help-circle"], ["state": 388, "unique_id": "pedometer_distance", "icon": "mdi:hiking", "type": "sensor"], ["icon": "mdi:stairs-up", "type": "sensor", "unique_id": "pedometer_floors_ascended", "state": 1], ["icon": "mdi:stairs-down", "unique_id": "pedometer_floors_descended", "type": "sensor", "state": 3], ["icon": "mdi:walk", "unique_id": "pedometer_steps", "type": "sensor", "state": 544], ["state": 1, "type": "sensor", "icon": "mdi:speedometer", "unique_id": "pedometer_avg_active_pace"], ["attributes": [:], "unique_id": "battery_level", "state": 70, "icon": "mdi:battery-70", "type": "sensor"], ["attributes": ["Low Power Mode": false], "state": "Not Charging", "icon": "mdi:battery-70", "type": "sensor", "unique_id": "battery_state"], ["unique_id": "storage", "state": "30.64", "attributes": ["Available (Opportunistic)": "78,32 GB", "Available": "39,14 GB", "Available (Important)": "104,89 GB", "Total": "255,64 GB"], "type": "sensor", "icon": "mdi:database"], ["icon": "mdi:wifi", "state": "SSID", "type": "sensor", "unique_id": "connectivity_ssid"], ["state": "f0:XX:XX:XX:XX:XX", "unique_id": "connectivity_bssid", "icon": "mdi:wifi-star", "type": "sensor"], ["unique_id": "connectivity_connection_type", "icon": "mdi:signal", "type": "sensor", "attributes": ["Cellular Technology": "5G"], "state": "Cellular"], ["state": "--", "type": "sensor", "unique_id": "connectivity_sim_1", "icon": "mdi:sim", "attributes": ["Mobile Network Code": "XXXXX", "Current Radio Technology": "5G Non-Standalone", "Allows VoIP": true, "ISO Country Code": "--", "Mobile Country Code": "XXXXX", "Carrier Name": "--", "Carrier ID": "0000000000000000"]], ["icon": "mdi:sim", "attributes": ["ISO Country Code": "--", "Mobile Network Code": "XXXXX", "Allows VoIP": true, "Carrier Name": "--", "Carrier ID": "0000000100000002", "Mobile Country Code": "XXXXX"], "type": "sensor", "unique_id": "connectivity_sim_2", "state": "--"], ["icon": "mdi:moon-waning-crescent", "unique_id": "focus", "type": "binary_sensor", "state": false], ["icon": "mdi:cellphone-wireless", "type": "sensor", "unique_id": "last_update_trigger", "state": "Watch Context"], ["unique_id": "watch-battery", "icon": "mdi:battery-70", "type": "sensor", "state": 75], ["state": "Not Charging", "type": "sensor", "icon": "mdi:battery-70", "unique_id": "watch-battery-state"], ["type": "sensor", "unique_id": "app-version", "state": "2025.2"], ["icon": "mdi:map", "state": "Authorized Always", "unique_id": "location-permission", "type": "sensor"], ["icon": "mdi:volume-high", "unique_id": "iphone-audio-output", "type": "sensor", "state": "Built-in Speaker"]], localMetadata: nil))
2025-04-05 11:12:50.907 AM [Info] [webhookmanager-data] [WebhookManager.swift:637] urlSession(_:task:didCompleteWithError:) > ignoring cancelled task taskKey(session: non-background, task: 43)
2025-04-05 11:12:50.956 AM [Info] [main] [HAAPI.swift:888] UpdateSensors(trigger:limitedTo:location:) > updating sensors ["activity", "pedometer_distance", "pedometer_floors_ascended", "pedometer_floors_descended", "pedometer_steps", "pedometer_avg_active_pace", "battery_level", "battery_state", "storage", "connectivity_ssid", "connectivity_bssid", "connectivity_connection_type", "connectivity_sim_1", "connectivity_sim_2", "focus", "last_update_trigger", "watch-battery", "watch-battery-state", "app-version", "location-permission", "iphone-audio-output"]
2025-04-05 11:12:50.956 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:12:50.958 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 45), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseUpdateSensors), request(WebhookRequest(type: "update_sensor_states", data: [["unique_id": "activity", "type": "sensor", "state": "Unknown", "icon": "mdi:help-circle", "attributes": ["Types": ["Unknown"], "Confidence": "High"]], ["unique_id": "pedometer_distance", "state": 388, "icon": "mdi:hiking", "type": "sensor"], ["type": "sensor", "icon": "mdi:stairs-up", "unique_id": "pedometer_floors_ascended", "state": 1], ["unique_id": "pedometer_floors_descended", "icon": "mdi:stairs-down", "state": 3, "type": "sensor"], ["type": "sensor", "icon": "mdi:walk", "state": 544, "unique_id": "pedometer_steps"], ["state": 1, "unique_id": "pedometer_avg_active_pace", "icon": "mdi:speedometer", "type": "sensor"], ["state": 70, "icon": "mdi:battery-70", "unique_id": "battery_level", "type": "sensor", "attributes": [:]], ["icon": "mdi:battery-70", "attributes": ["Low Power Mode": false], "state": "Not Charging", "type": "sensor", "unique_id": "battery_state"], ["unique_id": "storage", "attributes": ["Available (Important)": "104,89 GB", "Available": "39,14 GB", "Available (Opportunistic)": "78,32 GB", "Total": "255,64 GB"], "type": "sensor", "icon": "mdi:database", "state": "30.64"], ["type": "sensor", "unique_id": "connectivity_ssid", "icon": "mdi:wifi-off", "state": "Not Connected"], ["state": "Not Connected", "icon": "mdi:wifi-off", "type": "sensor", "unique_id": "connectivity_bssid"], ["icon": "mdi:signal", "type": "sensor", "attributes": ["Cellular Technology": "5G"], "state": "Cellular", "unique_id": "connectivity_connection_type"], ["unique_id": "connectivity_sim_1", "state": "--", "attributes": ["Mobile Country Code": "XXXXX", "Carrier Name": "--", "Carrier ID": "0000000000000000", "ISO Country Code": "--", "Mobile Network Code": "XXXXX", "Current Radio Technology": "5G Non-Standalone", "Allows VoIP": true], "type": "sensor", "icon": "mdi:sim"], ["type": "sensor", "state": "--", "unique_id": "connectivity_sim_2", "attributes": ["Carrier Name": "--", "Carrier ID": "0000000100000002", "ISO Country Code": "--", "Allows VoIP": true, "Mobile Country Code": "XXXXX", "Mobile Network Code": "XXXXX"], "icon": "mdi:sim"], ["icon": "mdi:moon-waning-crescent", "state": false, "unique_id": "focus", "type": "binary_sensor"], ["state": "Watch Context", "icon": "mdi:cellphone-wireless", "unique_id": "last_update_trigger", "type": "sensor"], ["type": "sensor", "state": 75, "unique_id": "watch-battery", "icon": "mdi:battery-70"], ["state": "Not Charging", "type": "sensor", "unique_id": "watch-battery-state", "icon": "mdi:battery-70"], ["type": "sensor", "state": "2025.2", "unique_id": "app-version"], ["type": "sensor", "state": "Authorized Always", "unique_id": "location-permission", "icon": "mdi:map"], ["unique_id": "iphone-audio-output", "type": "sensor", "icon": "mdi:volume-high", "state": "Built-in Speaker"]], localMetadata: nil))
2025-04-05 11:12:50.959 AM [Info] [webhookmanager-data] [WebhookManager.swift:637] urlSession(_:task:didCompleteWithError:) > ignoring cancelled task taskKey(session: non-background, task: 44)
2025-04-05 11:12:51.165 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: non-background, task: 45), type(WebhookResponseUpdateSensors), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "update_sensor_states", data: Optional([["state": "Unknown", "type": "sensor", "attributes": ["Confidence": "High", "Types": ["Unknown"]], "unique_id": "activity", "icon": "mdi:help-circle"], ["unique_id": "pedometer_distance", "type": "sensor", "state": 388, "icon": "mdi:hiking"], ["state": 1, "unique_id": "pedometer_floors_ascended", "icon": "mdi:stairs-up", "type": "sensor"], ["state": 3, "type": "sensor", "icon": "mdi:stairs-down", "unique_id": "pedometer_floors_descended"], ["state": 544, "unique_id": "pedometer_steps", "type": "sensor", "icon": "mdi:walk"], ["icon": "mdi:speedometer", "state": 1, "unique_id": "pedometer_avg_active_pace", "type": "sensor"], ["state": 70, "type": "sensor", "icon": "mdi:battery-70", "attributes": [:], "unique_id": "battery_level"], ["unique_id": "battery_state", "type": "sensor", "icon": "mdi:battery-70", "state": "Not Charging", "attributes": ["Low Power Mode": false]], ["type": "sensor", "state": "30.64", "icon": "mdi:database", "attributes": ["Available": "39,14 GB", "Total": "255,64 GB", "Available (Opportunistic)": "78,32 GB", "Available (Important)": "104,89 GB"], "unique_id": "storage"], ["type": "sensor", "state": "Not Connected", "icon": "mdi:wifi-off", "unique_id": "connectivity_ssid"], ["unique_id": "connectivity_bssid", "type": "sensor", "state": "Not Connected", "icon": "mdi:wifi-off"], ["attributes": ["Cellular Technology": "5G"], "state": "Cellular", "icon": "mdi:signal", "type": "sensor", "unique_id": "connectivity_connection_type"], ["state": "--", "type": "sensor", "unique_id": "connectivity_sim_1", "attributes": ["Carrier Name": "--", "Carrier ID": "0000000000000000", "Mobile Country Code": "XXXXX", "ISO Country Code": "--", "Current Radio Technology": "5G Non-Standalone", "Mobile Network Code": "XXXXX", "Allows VoIP": true], "icon": "mdi:sim"], ["unique_id": "connectivity_sim_2", "state": "--", "icon": "mdi:sim", "attributes": ["Allows VoIP": true, "Mobile Network Code": "XXXXX", "ISO Country Code": "--", "Mobile Country Code": "XXXXX", "Carrier Name": "--", "Carrier ID": "0000000100000002"], "type": "sensor"], ["unique_id": "focus", "state": false, "type": "binary_sensor", "icon": "mdi:moon-waning-crescent"], ["type": "sensor", "state": "Watch Context", "unique_id": "last_update_trigger", "icon": "mdi:cellphone-wireless"], ["unique_id": "watch-battery", "state": 75, "icon": "mdi:battery-70", "type": "sensor"], ["unique_id": "watch-battery-state", "state": "Not Charging", "type": "sensor", "icon": "mdi:battery-70"], ["unique_id": "app-version", "state": "2025.2", "type": "sensor"], ["state": "Authorized Always", "icon": "mdi:map", "unique_id": "location-permission", "type": "sensor"], ["icon": "mdi:volume-high", "unique_id": "iphone-audio-output", "type": "sensor", "state": "Built-in Speaker"]]), localMetadata: nil)), statusCode(200), body({
    activity =     {
        success = 1;
    };
    "app-version" =     {
        success = 1;
    };
    "battery_level" =     {
        success = 1;
    };
    "battery_state" =     {
        success = 1;
    };
    "connectivity_bssid" =     {
        success = 1;
    };
    "connectivity_connection_type" =     {
        success = 1;
    };
    "connectivity_sim_1" =     {
        success = 1;
    };
    "connectivity_sim_2" =     {
        success = 1;
    };
    "connectivity_ssid" =     {
        success = 1;
    };
    focus =     {
        success = 1;
    };
    "iphone-audio-output" =     {
        success = 1;
    };
    "last_update_trigger" =     {
        success = 1;
    };
    "location-permission" =     {
        success = 1;
    };
    "pedometer_avg_active_pace" =     {
        success = 1;
    };
    "pedometer_distance" =     {
        success = 1;
    };
    "pedometer_floors_ascended" =     {
        success = 1;
    };
    "pedometer_floors_descended" =     {
        success = 1;
    };
    "pedometer_steps" =     {
        success = 1;
    };
    storage =     {
        success = 1;
    };
    "watch-battery" =     {
        success = 1;
    };
    "watch-battery-state" =     {
        success = 1;
    };
})
2025-04-05 11:12:51.868 AM [Verbose] [main] [WatchCommunicatorService.swift:45] setup() > Received context: ["activeFamilies", "watchModel", "watchBattery", "complications", "watchVersion", "servers", "watchBatteryState"] ["activeFamilies": <__NSSingleObjectArrayI 0x145b2c660>(
graphicCircular
)
, "watchModel": Watch7,5, "watchBattery": 0.75, "complications": <__NSArray0 0xxxxx20360>(

)
, "watchVersion": 11.3.1, "servers": <...>, "watchBatteryState": 1]
2025-04-05 11:12:52.068 AM [Info] [main] [HAAPI.swift:888] UpdateSensors(trigger:limitedTo:location:) > updating sensors ["activity", "pedometer_distance", "pedometer_floors_ascended", "pedometer_floors_descended", "pedometer_steps", "pedometer_avg_active_pace", "battery_level", "battery_state", "storage", "connectivity_ssid", "connectivity_bssid", "connectivity_connection_type", "connectivity_sim_2", "connectivity_sim_1", "focus", "last_update_trigger", "watch-battery", "watch-battery-state", "app-version", "location-permission", "iphone-audio-output"]
2025-04-05 11:12:52.069 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:12:52.077 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 46), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseUpdateSensors), request(WebhookRequest(type: "update_sensor_states", data: [["state": "Unknown", "attributes": ["Types": ["Unknown"], "Confidence": "High"], "type": "sensor", "icon": "mdi:help-circle", "unique_id": "activity"], ["type": "sensor", "state": 388, "unique_id": "pedometer_distance", "icon": "mdi:hiking"], ["state": 1, "icon": "mdi:stairs-up", "unique_id": "pedometer_floors_ascended", "type": "sensor"], ["state": 3, "type": "sensor", "icon": "mdi:stairs-down", "unique_id": "pedometer_floors_descended"], ["unique_id": "pedometer_steps", "icon": "mdi:walk", "type": "sensor", "state": 544], ["icon": "mdi:speedometer", "type": "sensor", "unique_id": "pedometer_avg_active_pace", "state": 1], ["icon": "mdi:battery-70", "unique_id": "battery_level", "state": 70, "type": "sensor", "attributes": [:]], ["icon": "mdi:battery-70", "attributes": ["Low Power Mode": false], "type": "sensor", "unique_id": "battery_state", "state": "Not Charging"], ["icon": "mdi:database", "type": "sensor", "unique_id": "storage", "state": "30.64", "attributes": ["Total": "255,64 GB", "Available (Important)": "104,89 GB", "Available (Opportunistic)": "78,32 GB", "Available": "39,14 GB"]], ["unique_id": "connectivity_ssid", "icon": "mdi:wifi-off", "type": "sensor", "state": "Not Connected"], ["state": "Not Connected", "unique_id": "connectivity_bssid", "icon": "mdi:wifi-off", "type": "sensor"], ["icon": "mdi:signal", "state": "Cellular", "type": "sensor", "attributes": ["Cellular Technology": "5G"], "unique_id": "connectivity_connection_type"], ["unique_id": "connectivity_sim_2", "state": "--", "attributes": ["Mobile Network Code": "XXXXX", "Carrier Name": "--", "ISO Country Code": "--", "Allows VoIP": true, "Carrier ID": "0000000100000002", "Mobile Country Code": "XXXXX"], "type": "sensor", "icon": "mdi:sim"], ["type": "sensor", "icon": "mdi:sim", "unique_id": "connectivity_sim_1", "attributes": ["Mobile Country Code": "XXXXX", "ISO Country Code": "--", "Carrier ID": "0000000000000000", "Mobile Network Code": "XXXXX", "Carrier Name": "--", "Current Radio Technology": "5G Non-Standalone", "Allows VoIP": true], "state": "--"], ["state": false, "icon": "mdi:moon-waning-crescent", "type": "binary_sensor", "unique_id": "focus"], ["unique_id": "last_update_trigger", "state": "Watch Context", "icon": "mdi:cellphone-wireless", "type": "sensor"], ["state": 75, "type": "sensor", "icon": "mdi:battery-70", "unique_id": "watch-battery"], ["icon": "mdi:battery-70", "unique_id": "watch-battery-state", "type": "sensor", "state": "Not Charging"], ["state": "2025.2", "type": "sensor", "unique_id": "app-version"], ["icon": "mdi:map", "unique_id": "location-permission", "type": "sensor", "state": "Authorized Always"], ["icon": "mdi:volume-high", "type": "sensor", "unique_id": "iphone-audio-output", "state": "Built-in Speaker"]], localMetadata: nil))
2025-04-05 11:12:52.122 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: backgroundOnly
2025-04-05 11:12:52.217 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: non-background, task: 46), type(WebhookResponseUpdateSensors), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "update_sensor_states", data: Optional([["attributes": ["Confidence": "High", "Types": ["Unknown"]], "icon": "mdi:help-circle", "unique_id": "activity", "type": "sensor", "state": "Unknown"], ["state": 388, "icon": "mdi:hiking", "type": "sensor", "unique_id": "pedometer_distance"], ["state": 1, "unique_id": "pedometer_floors_ascended", "icon": "mdi:stairs-up", "type": "sensor"], ["icon": "mdi:stairs-down", "type": "sensor", "unique_id": "pedometer_floors_descended", "state": 3], ["state": 544, "icon": "mdi:walk", "unique_id": "pedometer_steps", "type": "sensor"], ["icon": "mdi:speedometer", "unique_id": "pedometer_avg_active_pace", "state": 1, "type": "sensor"], ["icon": "mdi:battery-70", "unique_id": "battery_level", "state": 70, "type": "sensor", "attributes": [:]], ["unique_id": "battery_state", "state": "Not Charging", "type": "sensor", "attributes": ["Low Power Mode": false], "icon": "mdi:battery-70"], ["state": "30.64", "attributes": ["Available (Opportunistic)": "78,32 GB", "Total": "255,64 GB", "Available (Important)": "104,89 GB", "Available": "39,14 GB"], "icon": "mdi:database", "type": "sensor", "unique_id": "storage"], ["icon": "mdi:wifi-off", "unique_id": "connectivity_ssid", "type": "sensor", "state": "Not Connected"], ["state": "Not Connected", "icon": "mdi:wifi-off", "unique_id": "connectivity_bssid", "type": "sensor"], ["type": "sensor", "state": "Cellular", "attributes": ["Cellular Technology": "5G"], "unique_id": "connectivity_connection_type", "icon": "mdi:signal"], ["type": "sensor", "state": "--", "unique_id": "connectivity_sim_2", "icon": "mdi:sim", "attributes": ["Mobile Network Code": "XXXXX", "Allows VoIP": true, "Carrier ID": "0000000100000002", "Carrier Name": "--", "ISO Country Code": "--", "Mobile Country Code": "XXXXX"]], ["unique_id": "connectivity_sim_1", "attributes": ["Mobile Country Code": "XXXXX", "Carrier Name": "--", "Carrier ID": "0000000000000000", "ISO Country Code": "--", "Mobile Network Code": "XXXXX", "Current Radio Technology": "5G Non-Standalone", "Allows VoIP": true], "state": "--", "type": "sensor", "icon": "mdi:sim"], ["state": false, "unique_id": "focus", "icon": "mdi:moon-waning-crescent", "type": "binary_sensor"], ["icon": "mdi:cellphone-wireless", "state": "Watch Context", "type": "sensor", "unique_id": "last_update_trigger"], ["state": 75, "type": "sensor", "unique_id": "watch-battery", "icon": "mdi:battery-70"], ["state": "Not Charging", "icon": "mdi:battery-70", "type": "sensor", "unique_id": "watch-battery-state"], ["unique_id": "app-version", "state": "2025.2", "type": "sensor"], ["type": "sensor", "unique_id": "location-permission", "state": "Authorized Always", "icon": "mdi:map"], ["type": "sensor", "unique_id": "iphone-audio-output", "icon": "mdi:volume-high", "state": "Built-in Speaker"]]), localMetadata: nil)), statusCode(200), body({
    activity =     {
        success = 1;
    };
    "app-version" =     {
        success = 1;
    };
    "battery_level" =     {
        success = 1;
    };
    "battery_state" =     {
        success = 1;
    };
    "connectivity_bssid" =     {
        success = 1;
    };
    "connectivity_connection_type" =     {
        success = 1;
    };
    "connectivity_sim_1" =     {
        success = 1;
    };
    "connectivity_sim_2" =     {
        success = 1;
    };
    "connectivity_ssid" =     {
        success = 1;
    };
    focus =     {
        success = 1;
    };
    "iphone-audio-output" =     {
        success = 1;
    };
    "last_update_trigger" =     {
        success = 1;
    };
    "location-permission" =     {
        success = 1;
    };
    "pedometer_avg_active_pace" =     {
        success = 1;
    };
    "pedometer_distance" =     {
        success = 1;
    };
    "pedometer_floors_ascended" =     {
        success = 1;
    };
    "pedometer_floors_descended" =     {
        success = 1;
    };
    "pedometer_steps" =     {
        success = 1;
    };
    storage =     {
        success = 1;
    };
    "watch-battery" =     {
        success = 1;
    };
    "watch-battery-state" =     {
        success = 1;
    };
})
2025-04-05 11:12:53.117 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: immediatelyReachable
2025-04-05 11:12:55.396 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: backgroundOnly
2025-04-05 11:12:56.566 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: immediatelyReachable
2025-04-05 11:12:56.681 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: backgroundOnly
2025-04-05 11:12:57.705 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: immediatelyReachable
2025-04-05 11:13:00.675 AM [Verbose] [main] [WatchCommunicatorService.swift:59] setupMessages() > Received magicItemPressed InteractiveImmediateMessage(identifier: "magicItemPressed", content: ["itemType": script, "itemId": script.open_home_door, "serverId": XXXX-XXX-XXX-XXX-XXXX], reply: (Function)) ["itemType": script, "itemId": script.open_home_door, "serverId": XXXX-XXX-XXX-XXX-XXXX]
2025-04-05 11:13:00.691 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:13:00.693 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 47), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseServiceCall), request(WebhookRequest(type: "call_service", data: ["service_data": [:], "domain": "script", "service": "open_home_door"], localMetadata: nil))
2025-04-05 11:13:01.688 AM [Verbose] [main] [ClientEventStore.swift:14] addEvent(_:) > Adding event: Called service: script.open_home_door, [:]
2025-04-05 11:13:01.688 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: non-background, task: 47), type(WebhookResponseServiceCall), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "call_service", data: Optional(["domain": "script", "service_data": [:], "service": "open_home_door"]), localMetadata: nil)), statusCode(200), body({
})
2025-04-05 11:13:01.831 AM [Verbose] [main] [ClientEventStore.swift:58] saveJSONData(_:) > JSON saved successfully for client events, file URL: file:///private/var/mobile/Containers/Shared/AppGroup/2EB7A8EA-8212-44B9-8101-57E1BE9EFEF4/databases/clientEvents.json
2025-04-05 11:13:26.716 AM [Error] [main] [BackgroundTask.swift:50] execute(withName:beginBackgroundTask:endBackgroundTask:wrapping:) > out of time for background task webhook-send 253
2025-04-05 11:13:26.717 AM [Info] [main] [Environment.swift:56] init() > PromiseKit:cauterized-error: outOfTime
2025-04-05 11:16:40.078 AM [Info] [main] [Environment.swift:73] init() > WebSocket: Peer closed
2025-04-05 11:16:40.080 AM [Info] [main] [Environment.swift:73] init() > WebSocket: phase transition to disconnected(error: nil, forReset: false)
2025-04-05 11:16:40.080 AM [Info] [main] [Environment.swift:73] init() > WebSocket: disconnecting; permanently: false, error: nil
2025-04-05 11:16:40.080 AM [Info] [main] [Environment.swift:73] init() > WebSocket: phase transition to disconnected(error: nil, forReset: true)
2025-04-05 11:16:40.081 AM [Info] [main] [Environment.swift:73] init() > WebSocket: connecting using HAConnectionInfo(url: https://XXXXXXXXX.ui.nabu.casa, userAgent: Optional("Home Assistant/2025.2 (io.robbie.HomeAssistant; build:2025.1178; iOS 18.4.0)"), engine: nil, evaluateCertificate: Optional((Function)))
2025-04-05 11:16:40.091 AM [Info] [main] [SensorContainer.swift:223] updateSignaled(from:) > live update triggering from ConnectivitySensor
2025-04-05 11:16:40.518 AM [Verbose] [main] [WebViewExternalMessageHandler.swift:197] sendExternalBus(message:) > sending {"id":-1,"command":"restart","type":"command"}
2025-04-05 11:16:40.518 AM [Error] [main] [WebViewExternalMessageHandler.swift:200] sendExternalBus(message:) > failed to fire message to externalBus: Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}
2025-04-05 11:16:40.520 AM [Verbose] [main] [ClientEventStore.swift:14] addEvent(_:) > Adding event: Background fetch activated, [:]
2025-04-05 11:16:40.628 AM [Verbose] [main] [ClientEventStore.swift:58] saveJSONData(_:) > JSON saved successfully for client events, file URL: file:///private/var/mobile/Containers/Shared/AppGroup/2EB7A8EA-8212-44B9-8101-57E1BE9EFEF4/databases/clientEvents.json
2025-04-05 11:16:40.656 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:130] configure(managers:) > manager SSID is active: true
2025-04-05 11:16:40.657 AM [Verbose] [main] [WatchCommunicatorService.swift:31] setup() > Reachability changed: backgroundOnly
2025-04-05 11:16:40.658 AM [Verbose] [main] [ConnectivityWrapper.swift:113] syncNetworkInformation() > Current SSID: Optional("SSID"), current BSSID: Optional("f0:XX:XX:XX:XX:XX")
2025-04-05 11:16:40.660 AM [Error] [main] [WebhookManager.swift:672] urlSession(_:task:didCompleteWithError:) > failed request to XXXX-XXX-XXX-XXX-XXXX for WebhookResponseServiceCall: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x1455b63d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <D559DC11-CADD-49F5-A813-C7EBD9896F02>.<42>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <D559DC11-CADD-49F5-A813-C7EBD9896F02>.<42>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://192.168.50.XXX:8123/api/webhook/XXXXXXXXX, NSErrorFailingURLKey=http://192.168.50.XXX:8123/api/webhook/XXXXXXXXX, _kCFStreamErrorDomainKey=4}
2025-04-05 11:16:40.660 AM [Error] [webhookmanager-data] [WebhookManager.swift:337] send(identifier:server:request:) > in-background non-background failed: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x1455b63d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <D559DC11-CADD-49F5-A813-C7EBD9896F02>.<42>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <D559DC11-CADD-49F5-A813-C7EBD9896F02>.<42>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://192.168.50.XXX:8123/api/webhook/XXXXXXXXX, NSErrorFailingURLKey=http://192.168.50.XXX:8123/api/webhook/XXXXXXXXX, _kCFStreamErrorDomainKey=4}
2025-04-05 11:16:40.661 AM [Info] [main] [Environment.swift:73] init() > WebSocket: Viability changed: true
2025-04-05 11:16:40.661 AM [Info] [main] [Environment.swift:73] init() > WebSocket: connected with headers: ["Connection": "upgrade", "Server": "Python/3.13 aiohttp/3.11.16", "Sec-WebSocket-Accept": "57b2Rn/PFsnJ7tzzpP55vSsm2ac=", "Upgrade": "websocket", "Sec-WebSocket-Extensions": "permessage-deflate", "Date": "Sat, 05 Apr 2025 09:16:40 GMT"]
2025-04-05 11:16:40.661 AM [Info] [main] [Environment.swift:73] init() > WebSocket: phase transition to auth
2025-04-05 11:16:40.663 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Received: auth: required
2025-04-05 11:16:40.664 AM [Verbose] [main] [CLLocationManager+OneShotLocation.swift:256] locationManager(_:didUpdateLocations:) > got raw locations [<+XX.XX,+XX.XX> +/- 8.11m (speed -1.00 mps / course -1.00) @ 05.04.2025, 11:16:40 AM Central European Summer Time] and turned into potential: [coordinate CLLocationCoordinate2D(latitude: XX.XX, longitude: XX.XX) accuracy 8.113293784383758 from 2025-04-05 9:16:40 AM +0000 quality perfect]
2025-04-05 11:16:40.664 AM [Info] [main] [CLLocationManager+OneShotLocation.swift:230] checkPotentialLocations(outOfTime:) > Got a perfect location!
2025-04-05 11:16:40.668 AM [Verbose] [main] [Realm+Initialization.swift:95] getRealm(objectTypes:) > Current schema version 28
2025-04-05 11:16:40.668 AM [Verbose] [main] [Realm+Initialization.swift:100] getRealm(objectTypes:) > Schema version defined: 28
2025-04-05 11:16:40.670 AM [Info] [main] [WatchHelpers.swift:68] SyncWatchContext() > updated context
2025-04-05 11:16:40.670 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:78] updateManagers() > 
2025-04-05 11:16:40.671 AM [Verbose] [com.apple.root.user-initiated-qos] [Realm+Initialization.swift:95] getRealm(objectTypes:) > Current schema version 28
2025-04-05 11:16:40.671 AM [Verbose] [com.apple.root.user-initiated-qos] [Realm+Initialization.swift:100] getRealm(objectTypes:) > Schema version defined: 28
2025-04-05 11:16:40.672 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Sending: (auth)
2025-04-05 11:16:40.674 AM [Info] [main] [WebViewController.swift:744] loadActiveURLIfNeeded() > not loading, in background
2025-04-05 11:16:40.674 AM [Verbose] [main] [Realm+Initialization.swift:95] getRealm(objectTypes:) > Current schema version 28
2025-04-05 11:16:40.675 AM [Verbose] [main] [Realm+Initialization.swift:100] getRealm(objectTypes:) > Schema version defined: 28
2025-04-05 11:16:40.691 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: webhook-io.robbie.HomeAssistant, task: 6), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseServiceCall), request(WebhookRequest(type: "call_service", data: ["service": "open_home_door", "service_data": [:], "domain": "script"], localMetadata: nil))
2025-04-05 11:16:40.708 AM [Info] [main] [Environment.swift:56] init() > PromiseKit:cauterized-error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x1455b63d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <D559DC11-CADD-49F5-A813-C7EBD9896F02>.<42>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <D559DC11-CADD-49F5-A813-C7EBD9896F02>.<42>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://192.168.50.XXX:8123/api/webhook/XXXXXXXXX, NSErrorFailingURLKey=http://192.168.50.XXX:8123/api/webhook/XXXXXXXXX, _kCFStreamErrorDomainKey=4}
2025-04-05 11:16:40.708 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Received: auth: ok(version: "2025.4.0")
2025-04-05 11:16:40.708 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:93] updateManagers() > configuring push for SSID: [XXXX-XXX-XXX-XXX-XXXX]
2025-04-05 11:16:40.708 AM [Verbose] [main] [NotificationManagerLocalPushInterfaceExtension.swift:141] configure(managers:) > computed managers: [XXXX-XXX-XXX-XXX-XXXX: [<NEAppPushManager: 0xxxxxxxxxx0>]]
2025-04-05 11:16:40.708 AM [Info] [main] [Environment.swift:73] init() > WebSocket: phase transition to command(version: "2025.4.0")
2025-04-05 11:16:40.709 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Sending: {"event_type":"component_loaded","id":63,"type":"subscribe_events"}
2025-04-05 11:16:40.709 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Sending: {"event_type":"core_config_updated","id":64,"type":"subscribe_events"}
2025-04-05 11:16:40.709 AM [Info] [com.apple.root.user-initiated-qos] [RealmScene.swift:71] willDelete(objects:server:realm:) > deleting actions []
2025-04-05 11:16:40.710 AM [Info] [main] [HAAPI.swift:550] SubmitLocation(updateType:location:zone:) > Location update payload: ["altitude": 278.9578283135009, "gps": [XX.XX, XX.XX], "battery": 65, "vertical_accuracy": 30.0, "gps_accuracy": 8.113293784383758]
2025-04-05 11:16:40.710 AM [Info] [main] [HAAPI.swift:888] UpdateSensors(trigger:limitedTo:location:) > updating sensors ["activity", "pedometer_distance", "pedometer_floors_ascended", "pedometer_floors_descended", "pedometer_steps", "pedometer_avg_active_pace", "battery_level", "battery_state", "storage", "connectivity_ssid", "connectivity_bssid", "connectivity_connection_type", "connectivity_sim_1", "connectivity_sim_2", "focus", "last_update_trigger", "watch-battery", "watch-battery-state", "app-version", "location-permission", "iphone-audio-output"]
2025-04-05 11:16:40.730 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:16:40.730 AM [Info] [main] [NotificationManagerLocalPushInterfaceExtension.swift:191] updateManager(existingManager:ssid:servers:encoder:) > manager <NEAppPushManager: 0xxxxxxxxxx0> saved, error: nil
2025-04-05 11:16:40.731 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:16:40.731 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 48), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseLocation), request(WebhookRequest(type: "update_location", data: ["altitude": 278.9578283135009, "gps": [XX.XX, XX.XX], "battery": 65, "vertical_accuracy": 30.0, "gps_accuracy": 8.113293784383758], localMetadata: Optional(["zone_name": "(unknown)", "trigger": "Background Fetch"])))
2025-04-05 11:16:40.732 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 49), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseUpdateSensors), request(WebhookRequest(type: "update_sensor_states", data: [["type": "sensor", "unique_id": "activity", "state": "Stationary", "icon": "mdi:human-male", "attributes": ["Types": ["Stationary"], "Confidence": "High"]], ["icon": "mdi:hiking", "state": 397, "unique_id": "pedometer_distance", "type": "sensor"], ["unique_id": "pedometer_floors_ascended", "type": "sensor", "icon": "mdi:stairs-up", "state": 1], ["icon": "mdi:stairs-down", "type": "sensor", "state": 3, "unique_id": "pedometer_floors_descended"], ["type": "sensor", "icon": "mdi:walk", "state": 557, "unique_id": "pedometer_steps"], ["type": "sensor", "unique_id": "pedometer_avg_active_pace", "state": 1, "icon": "mdi:speedometer"], ["type": "sensor", "unique_id": "battery_level", "attributes": [:], "icon": "mdi:battery-60", "state": 65], ["state": "Not Charging", "type": "sensor", "unique_id": "battery_state", "attributes": ["Low Power Mode": false], "icon": "mdi:battery-60"], ["icon": "mdi:database", "state": "30.63", "unique_id": "storage", "attributes": ["Total": "255,64 GB", "Available": "39,12 GB", "Available (Opportunistic)": "78,30 GB", "Available (Important)": "104,87 GB"], "type": "sensor"], ["state": "Not Connected", "unique_id": "connectivity_ssid", "icon": "mdi:wifi-off", "type": "sensor"], ["unique_id": "connectivity_bssid", "state": "Not Connected", "type": "sensor", "icon": "mdi:wifi-off"], ["type": "sensor", "state": "Wi-Fi", "unique_id": "connectivity_connection_type", "icon": "mdi:wifi", "attributes": [:]], ["type": "sensor", "attributes": ["Carrier ID": "0000000000000000", "Carrier Name": "--", "Mobile Country Code": "XXXXX", "Mobile Network Code": "XXXXX", "Allows VoIP": true, "Current Radio Technology": "5G Non-Standalone", "ISO Country Code": "--"], "icon": "mdi:sim", "state": "--", "unique_id": "connectivity_sim_1"], ["attributes": ["Mobile Country Code": "XXXXX", "Carrier ID": "0000000100000002", "Carrier Name": "--", "Mobile Network Code": "XXXXX", "ISO Country Code": "--", "Allows VoIP": true], "state": "--", "type": "sensor", "unique_id": "connectivity_sim_2", "icon": "mdi:sim"], ["icon": "mdi:moon-waning-crescent", "state": false, "unique_id": "focus", "type": "binary_sensor"], ["icon": "mdi:cellphone-wireless", "unique_id": "last_update_trigger", "type": "sensor", "state": "Signaled"], ["state": 75, "icon": "mdi:battery-70", "type": "sensor", "unique_id": "watch-battery"], ["state": "Not Charging", "icon": "mdi:battery-70", "type": "sensor", "unique_id": "watch-battery-state"], ["type": "sensor", "unique_id": "app-version", "state": "2025.2"], ["unique_id": "location-permission", "type": "sensor", "icon": "mdi:map", "state": "Authorized Always"], ["icon": "mdi:volume-high", "state": "Built-in Speaker", "unique_id": "iphone-audio-output", "type": "sensor"]], localMetadata: nil))
2025-04-05 11:16:40.733 AM [Verbose] [main] [ClientEventStore.swift:14] addEvent(_:) > Adding event: Called service: script.open_home_door, [:]
2025-04-05 11:16:40.733 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: webhook-io.robbie.HomeAssistant, task: 6), type(WebhookResponseServiceCall), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "call_service", data: Optional(["service_data": [:], "service": "open_home_door", "domain": "script"]), localMetadata: nil)), statusCode(200), body({
})
2025-04-05 11:16:40.754 AM [Verbose] [main] [ClientEventStore.swift:58] saveJSONData(_:) > JSON saved successfully for client events, file URL: file:///private/var/mobile/Containers/Shared/AppGroup/2EB7A8EA-8212-44B9-8101-57E1BE9EFEF4/databases/clientEvents.json
2025-04-05 11:16:40.755 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Received: result success HARequestIdentifier(rawValue: 63)
2025-04-05 11:16:40.755 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: non-background, task: 48), type(WebhookResponseLocation), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "update_location", data: Optional(["battery": 65, "altitude": 278.9578283135009, "gps": [XX.XX, XX.XX], "gps_accuracy": 8.113293784383758, "vertical_accuracy": 30]), localMetadata: Optional(["zone_name": "(unknown)", "trigger": "Background Fetch"]))), statusCode(200), body({
})
2025-04-05 11:16:40.755 AM [Verbose] [main] [ClientEventStore.swift:14] addEvent(_:) > Adding event: Current location delivery triggered via background fetch, ["gps": Shared.AnyCodable(value: [XX.XX, XX.XX]), "altitude": Shared.AnyCodable(value: 278.9578283135009), "vertical_accuracy": Shared.AnyCodable(value: 30), "battery": Shared.AnyCodable(value: 65), "gps_accuracy": Shared.AnyCodable(value: 8.113293784383758)]
2025-04-05 11:16:40.770 AM [Verbose] [main] [ClientEventStore.swift:58] saveJSONData(_:) > JSON saved successfully for client events, file URL: file:///private/var/mobile/Containers/Shared/AppGroup/2EB7A8EA-8212-44B9-8101-57E1BE9EFEF4/databases/clientEvents.json
2025-04-05 11:16:40.771 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: non-background, task: 49), type(WebhookResponseUpdateSensors), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "update_sensor_states", data: Optional([["icon": "mdi:human-male", "state": "Stationary", "attributes": ["Types": ["Stationary"], "Confidence": "High"], "type": "sensor", "unique_id": "activity"], ["icon": "mdi:hiking", "state": 397, "unique_id": "pedometer_distance", "type": "sensor"], ["icon": "mdi:stairs-up", "state": 1, "type": "sensor", "unique_id": "pedometer_floors_ascended"], ["icon": "mdi:stairs-down", "type": "sensor", "state": 3, "unique_id": "pedometer_floors_descended"], ["type": "sensor", "unique_id": "pedometer_steps", "icon": "mdi:walk", "state": 557], ["type": "sensor", "unique_id": "pedometer_avg_active_pace", "state": 1, "icon": "mdi:speedometer"], ["state": 65, "icon": "mdi:battery-60", "attributes": [:], "type": "sensor", "unique_id": "battery_level"], ["icon": "mdi:battery-60", "type": "sensor", "unique_id": "battery_state", "state": "Not Charging", "attributes": ["Low Power Mode": false]], ["type": "sensor", "attributes": ["Available": "39,12 GB", "Available (Important)": "104,87 GB", "Total": "255,64 GB", "Available (Opportunistic)": "78,30 GB"], "icon": "mdi:database", "state": "30.63", "unique_id": "storage"], ["icon": "mdi:wifi-off", "type": "sensor", "state": "Not Connected", "unique_id": "connectivity_ssid"], ["icon": "mdi:wifi-off", "type": "sensor", "unique_id": "connectivity_bssid", "state": "Not Connected"], ["type": "sensor", "state": "Wi-Fi", "unique_id": "connectivity_connection_type", "attributes": [:], "icon": "mdi:wifi"], ["type": "sensor", "icon": "mdi:sim", "state": "--", "unique_id": "connectivity_sim_1", "attributes": ["Carrier ID": "0000000000000000", "Allows VoIP": true, "Carrier Name": "--", "Current Radio Technology": "5G Non-Standalone", "Mobile Network Code": "XXXXX", "Mobile Country Code": "XXXXX", "ISO Country Code": "--"]], ["unique_id": "connectivity_sim_2", "icon": "mdi:sim", "state": "--", "type": "sensor", "attributes": ["Carrier Name": "--", "Carrier ID": "0000000100000002", "Mobile Network Code": "XXXXX", "ISO Country Code": "--", "Mobile Country Code": "XXXXX", "Allows VoIP": true]], ["unique_id": "focus", "icon": "mdi:moon-waning-crescent", "type": "binary_sensor", "state": false], ["state": "Signaled", "type": "sensor", "icon": "mdi:cellphone-wireless", "unique_id": "last_update_trigger"], ["state": 75, "icon": "mdi:battery-70", "type": "sensor", "unique_id": "watch-battery"], ["type": "sensor", "icon": "mdi:battery-70", "state": "Not Charging", "unique_id": "watch-battery-state"], ["state": "2025.2", "unique_id": "app-version", "type": "sensor"], ["unique_id": "location-permission", "icon": "mdi:map", "type": "sensor", "state": "Authorized Always"], ["icon": "mdi:volume-high", "unique_id": "iphone-audio-output", "type": "sensor", "state": "Built-in Speaker"]]), localMetadata: nil)), statusCode(200), body({
    activity =     {
        success = 1;
    };
    "app-version" =     {
        success = 1;
    };
    "battery_level" =     {
        success = 1;
    };
    "battery_state" =     {
        success = 1;
    };
    "connectivity_bssid" =     {
        success = 1;
    };
    "connectivity_connection_type" =     {
        success = 1;
    };
    "connectivity_sim_1" =     {
        success = 1;
    };
    "connectivity_sim_2" =     {
        success = 1;
    };
    "connectivity_ssid" =     {
        success = 1;
    };
    focus =     {
        success = 1;
    };
    "iphone-audio-output" =     {
        success = 1;
    };
    "last_update_trigger" =     {
        success = 1;
    };
    "location-permission" =     {
        success = 1;
    };
    "pedometer_avg_active_pace" =     {
        success = 1;
    };
    "pedometer_distance" =     {
        success = 1;
    };
    "pedometer_floors_ascended" =     {
        success = 1;
    };
    "pedometer_floors_descended" =     {
        success = 1;
    };
    "pedometer_steps" =     {
        success = 1;
    };
    storage =     {
        success = 1;
    };
    "watch-battery" =     {
        success = 1;
    };
    "watch-battery-state" =     {
        success = 1;
    };
})
2025-04-05 11:16:40.771 AM [Info] [hakit-work-queue] [Environment.swift:73] init() > WebSocket: Received: result success HARequestIdentifier(rawValue: 64)
2025-04-05 11:16:40.860 AM [Verbose] [main] [Realm+Initialization.swift:95] getRealm(objectTypes:) > Current schema version 28
2025-04-05 11:16:40.860 AM [Verbose] [main] [Realm+Initialization.swift:100] getRealm(objectTypes:) > Schema version defined: 28
2025-04-05 11:16:40.862 AM [Info] [main] [HAAPI.swift:888] UpdateSensors(trigger:limitedTo:location:) > updating sensors ["activity", "pedometer_distance", "pedometer_floors_ascended", "pedometer_floors_descended", "pedometer_steps", "pedometer_avg_active_pace", "battery_level", "battery_state", "storage", "connectivity_ssid", "connectivity_bssid", "connectivity_connection_type", "connectivity_sim_1", "connectivity_sim_2", "geocoded_location", "focus", "last_update_trigger", "watch-battery", "watch-battery-state", "app-version", "location-permission", "iphone-audio-output"]
2025-04-05 11:16:40.862 AM [Info] [webhookmanager-data] [WebhookManager.swift:335] send(identifier:server:request:) > in background, choosing to not use background session
2025-04-05 11:16:40.863 AM [Info] [webhookmanager-data] [WebhookManager.swift:432] send(on:server:identifier:request:waitForResponse:) > starting request: taskKey(session: non-background, task: 50), server(XXXX-XXX-XXX-XXX-XXXX), type(WebhookResponseUpdateSensors), request(WebhookRequest(type: "update_sensor_states", data: [["icon": "mdi:human-male", "state": "Stationary", "type": "sensor", "unique_id": "activity", "attributes": ["Confidence": "High", "Types": ["Stationary"]]],/../
2025-04-05 11:16:40.878 AM [Info] [webhookmanager-data] [WebhookManager.swift:659] urlSession(_:task:didCompleteWithError:) > got response: taskKey(session: non-background, task: 50), type(WebhookResponseUpdateSensors), server(XXXX-XXX-XXX-XXX-XXXX), request(WebhookRequest(type: "update_sensor_states", data: Optional([["unique_id": "activity", "attributes": ["Types": ["Stationary"], "Confidence": "High"], "type": "sensor", "icon": "mdi:human-male", "state": "Stationary"], /.../
    activity =     {
        success = 1;
    };
    "app-version" =     {
        success = 1;
    };
    "battery_level" =     {
        success = 1;
    };
    "battery_state" =     {
        success = 1;
    };
    "connectivity_bssid" =     {
        success = 1;
    };
    "connectivity_connection_type" =     {
        success = 1;
    };
    "connectivity_sim_1" =     {
        success = 1;
    };
    "connectivity_sim_2" =     {
        success = 1;
    };
    "connectivity_ssid" =     {
        success = 1;
    };
    focus =     {
        success = 1;
    };
    "geocoded_location" =     {
        success = 1;
    };
    "iphone-audio-output" =     {
        success = 1;
    };
    "last_update_trigger" =     {
        success = 1;
    };
    "location-permission" =     {
        success = 1;
    };
    "pedometer_avg_active_pace" =     {
        success = 1;
    };
    "pedometer_distance" =     {
        success = 1;
    };
    "pedometer_floors_ascended" =     {
        success = 1;
    };
    "pedometer_floors_descended" =     {
        success = 1;
    };
    "pedometer_steps" =     {
        success = 1;
    };
    storage =     {
        success = 1;
    };
    "watch-battery" =     {
        success = 1;
    };
    "watch-battery-state" =     {
        success = 1;
    };
})
```

</details>

**Comment by eMeF1** [comment]
Someone willing to pick it up? It just happened to me 15 minutes after I left home :(

**Comment by bgoncal** [comment]
It's fixed now.

**Comment by helder14** [comment]
Hi @bgoncal , still happening for me even with the latest version, this has been an ongoing issue for almost a year, I really would love to be able to select automations instead of scripts (even though I know I could trigger an automation with a script).

It would also be great to be able to add parameters like we were able to with the legacy iOS Actions(actionName, actionID, sourceDeviceID, sourceDeviceName, sourceDevicePermanentID,...) so we could add a condition the source needs to be the watch, at the moment, it just says it was triggered by the phone on both cases.

**Comment by udix** [comment]
Same here, with 2026.1 version I’m still experiencing the issue

**Comment by eMeF1** [comment]
@bgoncal It happened to me again a couple of days ago.

**Comment by helder14** [comment]
I don't know for anyone else but for me the the first trigger happens when I press it from my watch, and the second happens when the Home assistant app on my phone does a background update, or if I open it, then it updates and trigger the second one.

It kind like the app would trigger and put it on hold until it then does an update and triggers it again from that hold state.

**Comment by 5quirrel** [comment]
Still happening, lucky my neighbours haven't looted my garage

**Comment by helder14** [comment]
Still happening for me too, even when adding required confirmation, it still does it.
