### ISSUE TITLE
Strange overlay behavior in dialogs/menu bar

### ISSUE THREAD

**Issue by N3rdix** [home-assistant/iOS#3859]
**iOS device model, version and app version**

Model Name: iPhone 16
Software Version: 26.0
App version: 2025.9.3

**Home Assistant Core Version**

2025.9.4

**Describe the bug**
Not sure if this came with iOS 26, but it's at least a new behavior only in the app (no browser issue).
The more info dialog as well as the left menu bar seem to overlay incorrectly and the background is still in focus and scrollable.
This issue does not occur at the beginning when the app is opened initially, it more seems to come "later" when I open the app again.

See atached video:
https://github.com/user-attachments/assets/b4ec92dd-6bf2-46ba-8166-fb268f26f952

**To Reproduce**

**Expected behavior**
Overlay should avoid scrolling of the layers behind.

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
That's a bug in the frontend, it has been fixed in the latest Home Assistant beta though

**Comment by N3rdix** [comment]
thanks for the quick reply, then I will check out the Beta on my test server 👍 

Closing this issue

**Comment by N3rdix** [comment]
> That's a bug in the frontend, it has been fixed in the latest Home Assistant beta though

@bgoncal this is still an issue with HA 2025.10.3, seems not to be fixed. Shall I open an issue in the frontend repo?

**Comment by bgoncal** [comment]
Apologies, my previous information was incorrect, this is an iOS issue, fixed on iOS 26.1 beta, which should be released around next week (just an estimation)
