### ISSUE TITLE
Can not login to home assistant instance after iOS app upgrade (2019.1)

### ISSUE THREAD

**Issue by prakharsharma** [home-assistant/iOS#489]
I updated to the latest iOS app (2019.1). Since then I have been unable to connect to the home assistant instance running on my raspberry pi. I use a duckdns/letsencrypt setup and am able to connect via Safari (on my iphone). But, when I manually enter the same address in the iOS app and try to connect, it opens a webview which says "404 not found". I tried on my wife's phone and the same thing is happening over there. Will appreciate any help in trying to resolve this issue. Thanks!

**Comment by olbjan** [comment]
When you manually enter the address, please don't add the trailing / to the end. Also check if that trailing / is in your base_url: and if needed, remove it.

**Comment by christianwgd** [comment]
Even without the trailing slash, the login fails and the 404 message is shown. Seems you made breaking changes to the app, that requires updating the server version. At different places there is a document referenced called "Migrating to Home Assistant Companion 2019.1", but i event don't know what this companion is meant to be. Can somebody please clarify the changes and its dependencies? Thanks!

**Comment by christianwgd** [comment]
Ok, after some testing, i found that adding the changes under "Requirements" in that [doc]([https://companion.home-assistant.io/en/getting_started/migration.html#1---updating-the-ios-app-via-the-app-store](url)) seems to work, the iOS app is back again. Be cautious not adding existing integrations...

**Comment by TomBrien** [comment]
Glad this is working. As the original issue is resolved I’ll mark this as closed. If I’m wrong please feel free to reopen.

**Comment by prakharsharma** [comment]
This is still not working for me. Still get the same 404 not found issue. Has a fix for the issue being released? Is there a single definitive guide which can help me resolve the issues? If yes, I will really appreciate the pointer.

I am not sure why a breaking change was made for something which is being widely used - different app versions, different servers. This incident has really made a dent in my confidence in home-assistant in general. Not to mention the timing of this breaking change was really bad; when a lot of ppl were getting ready to travel for the thanksgiving break and all of a sudden you realize that your home automation/security system is unreliable.

**Comment by prakharsharma** [comment]
> Glad this is working. As the original issue is resolved I’ll mark this as closed. If I’m wrong please feel free to reopen.

@TomBrien it is not working and I can not reopen the issue.

**Comment by SeanPM5** [comment]
I understand your frustration @prakharsharma, nobody likes breaking changes, but sometimes they are hard to avoid. In this case the mobile app was almost completely rewritten.

The guide you should follow is [Migrating to Home Assistant Companion 2019.1](https://companion.home-assistant.io/en/getting_started/migration.html). First, make sure that your setup follows the "Requirements" section at the top. If that doesn't fix it, the other relevant part of the guide is step 4:
>If you get a 404 error when not using Nabu Casa. Please make sure that you are not including a trailing `/` when entering your URL manually or in `base_url:` entry in configuration.yaml if using the automatic discovery when on home network.

I've reopened the issue, please try those things and report back. If none of the above stuff I mentioned works, you'll have to provide some more information on your setup so that others can help you troubleshoot.

**Comment by TomBrien** [comment]
Hi just wondering if there is any news here. Hope you've got it working. We've had a few updates in the last week which address some of the setup issues

**Comment by TomBrien** [comment]
Closing this as stale. Let us know if there are issues and we can re open. As mentioned above there have been a lot of changes on this recently so hopefully it is working now
