### ISSUE TITLE
geolocation didn't update for travel across town

### ISSUE THREAD

**Issue by josh-m-sharpe** [home-assistant/iOS#923]
Model Name:  iPhone 8 Plus
Software Version: 13.6
App version: 2020.5.2

**Home Assistant Core Version**
0.114.0

**Describe the bug**

This evening I left my house and returned a few hours later.  After getting home, if I look at my HA dashboard, specifically, these two attributes(?):
<img width="105" alt="Screen Shot 2020-08-16 at 8 42 43 PM" src="https://user-images.githubusercontent.com/39473/90347903-25ae7200-e001-11ea-8551-5eaa7e6e0652.png">
I don't see any location changes that reflect leaving the house and returning.  The first one "Geocoded Location" has data for the last 24 hours, but it mostly just bounces back and forth between my house and the neighbors (this is fine, I attribute it to a weak GPS signal) (I'd add a screenshot but it's full of location data).  

The second one "Last Update Trigger" has a range of "Significant Location Change" for the last 12+ hours, but candidly I'm not sure what that means.  There doesn't seem to be a change in the bar/graph that reflects leaving the house and returning though.
![Screenshot_8_16_20__8_47_PM](https://user-images.githubusercontent.com/39473/90348009-dae12a00-e001-11ea-90e4-1d3721862fe0.jpg)

Worth noting that I've given 'Always' location access to Home Assistant.  So, in theory it should be able to poll location data regularly. 

**To Reproduce**
A bit unclear at this point - this is the first time I've noticed this discrepancy.

**Expected behavior**
I would've expected some location change to reflect that I left for a few hours and returned.  Is that a reasonable expectation?  I kinda thought this attribute could be used for some leaving/returning automations.  Have I mis-interpreted that?

**Comment by TomBrien** [comment]
When travelling the last update trigger is often "Significant Location Change". Can you check that the `device_tracker...` entity is not changing. In iOS settings>Home Assistant, are both "Background App Refresh" and "Mobile Data" enabled?

>  I kinda thought this attribute could be used for some leaving/returning automations. Have I mis-interpreted that? 

You could use the `sensor.xxx_geocoded_location` sensor for automatons however it may well not be the most reliable. You will probably have much better results if you use the `device_tracker.xxx` entity and define [zones](https://www.home-assistant.io/integrations/zone/) to cover areas you wish to trigger entry/exit automation from. For best results I would suggest bundling multiple device trackers (e.g. the app and wifi) into a [person](https://www.home-assistant.io/integrations/person/) entity. Geocoded location relies on Apple maps to resolve the location and thus may not always be reliable

**Comment by josh-m-sharpe** [comment]
I'm a few weeks away from being able to tinker with this again. I definitely will!

That said,  I can confirm that "Background App Refresh" and "Cellular Data" (not "Mobile Data") are both enabled in my app's settings.

Not sure it's relevant, but in my test setup, I hadn't exposed HA to the internet yet.  I suspect that piece is probably(?) required in order to have automations fire while I'm away.  However, I would also think that that the app on my phone should be able to track location until returning home and connecting to the wifi.  Maybe that's an incorrect assumption?

**Comment by TomBrien** [comment]
> Not sure it's relevant, but in my test setup, I hadn't exposed HA to the internet yet. I suspect that piece is probably(?) required in order to have automations fire while I'm away. However, I would also think that that the app on my phone should be able to track location until returning home and connecting to the wifi. Maybe that's an incorrect assumption?

Unfortunately the app does not store updates, it acts as just a view and communicates sensor/location updates if there is no connection the updates are no retried later. You may wish to comment on #901 as that is related to the behaviour you expected.

**Comment by vlumikero** [comment]
I’m having having similar symptoms as of August. To me it seems there’s a significant lag in the location updates, so if I take a walk in my neighborhood, I can see that my location on the map updates, but with perhaps a 5-10 minute lag. 

I’m on iOS 14 and HA 0.115.1. 

This is what it looks like when I arrive home. 

![74F53B90-3368-4813-9CD8-18CAA45631A4](https://user-images.githubusercontent.com/13744614/93701231-1e561900-fb17-11ea-93a0-01a7f0425f2f.jpeg)

**Comment by zacwest** [comment]
That sounds like a bug fixed in 2020.6. It's rolling out slowly over the next week but you can update to it now in the App Store manually.

**Comment by vlumikero** [comment]
Unfortunately the new app version did not fix the issue for me at least.

**Comment by zacwest** [comment]
With recent app updates, location changes are generally more accurate than since this ticket was created. The latest app also features a Location History screen which allows exporting some debug information about the location update. If you run into location errors, please open a new ticket.
